### PR TITLE
Pull request: Bug/fix draw finishing moment - closes #122

### LINKED ISSUE #122: draw controller finishes drawing on touch/click
While developing the testdrive and integrating a state manager into the build screen I discovered that the `DrawController` finishes drawing as soon as `touchMouseUp` is triggered. This means drawing gets finished with a single click/touch.

Ideally, drawing should only be finished if a valid path was drawn.

### PR DESCRIPTION
**Pull request by tombu**
This PR cares about the right moment to finish drawing. Until now a normal click/touch fired the `finishedDrawing` event. I introduced the `hasValidTotalLength` method on `Track`. By using this method in the draw controllers `onTouchMouseUp` it can be ensured that `finishedDrawing` is just called if the track is long enough, otherwise you have to redraw! - see #122

### CODE REVIEW

File: app/assets/javascripts/slotcars/shared/models/track.js.coffee [hunk 1]
```diff
@@ -44,6 +44,8 @@ Shared.Track = DS.Model.extend Shared.IdObservable,
 
   getTotalLength: -> (@get '_raphaelPath').get 'totalLength'
 
+  hasValidTotalLength: -> (@get '_raphaelPath').get('totalLength') > 400
```
Comment (DominikGuzei) [inline app/assets/javascripts/slotcars/shared/models/track.js.coffee]: Please move the `400` into its own constant like `MINIMUM_TRACK_LENGTH`

**Comment by DominikGuzei** [comment]
looks great when suggested fix is done! :+1:
